use crate::audio::player::RepeatMode;
use serde::{Deserialize, Serialize};

#[derive(
    Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, sqlx::Type,
)]
#[sqlx(type_name = "TEXT", rename_all = "snake_case")]
#[serde(rename_all = "snake_case")]
pub enum QualityTier {
    /// Low bandwidth or highly compressed streams
    Low,
    /// Standard streaming quality (Opus 128kbps, MP3 128kbps)
    Standard,
    /// High-quality lossy (MP3 320kbps, AAC 256kbps)
    High,
    /// Lossless formats (FLAC, ALAC, WAV)
    Lossless,
}

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, sqlx::Type)]
#[sqlx(type_name = "TEXT", rename_all = "lowercase")]
#[serde(rename_all = "lowercase")]
pub enum Platform {
    Youtube,
    Bandcamp,
    // Soundcloud,
    Local,
}

#[derive(Serialize, Debug, Deserialize, Clone, sqlx::FromRow)]
pub struct Song {
    pub id: Option<i64>,
    pub path: String,
    pub title: String,
    #[sqlx(json)]
    pub artists: Vec<String>,
    pub album_artist: String,
    pub album: String,
    pub duration_ms: u64,
    pub track_number: Option<i32>,
    pub genre: Option<String>,
    pub release_year: Option<i32>,
    pub cover_url: Option<String>,
    pub external_cover_url: Option<String>,
    pub lyrics: Option<String>,
    pub lyrics_source: Option<String>,

    /// Where did this specific file come from
    pub source: Platform,

    pub source_url: Option<String>,

    /// The unique ID assigned to the track by the platform
    pub source_item_id: Option<String>,

    /// Generated by normalizing artist + title (e.g., "chris-christodoulou-now-i-am-become-death")
    pub canonical_track_slug: String,

    /// Generated by normalizing artist + album (e.g., "chris-christodoulou-deadbolt")
    pub canonical_album_slug: String,

    /// Audio quality/bitrate indicator (QualityTier).
    pub quality_tier: QualityTier,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum DownloadType {
    Album,
    Playlist,
    Track,
}

#[derive(Serialize, Clone, Debug)]
pub struct PlayerState {
    pub current_song: Option<Song>,
    pub is_playing: bool,
    pub progress: f32,
    pub volume: f32,
    pub shuffle_mode: bool,
    pub repeat_mode: RepeatMode,
}

#[derive(Debug, serde::Serialize, serde::Deserialize, sqlx::FromRow)]
pub struct ArtistSummary {
    pub name: String,
    pub album_count: i32,
    pub cover_url: Option<String>,
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct Album {
    pub title: String,
    pub album_artist: String,
    pub cover_url: Option<String>,
    pub songs: Vec<Song>,
}
